[package]
name = "latte-core"
version = "${UPSTREAM_VERSION}"
edition = "2021"
license = "Apache-2.0"
description = "ScyllaDB benchmarking library (core from latte)"

[lib]
name = "latte_core"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
base64 = "0.22"
bytes = "1.0.1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive", "cargo", "env"] }
console = "0.15.0"
cpu-time = "1.0.0"
futures = "0.3"
hdrhistogram = "7.1.0"
hytra = "0.1.2"
itertools = "0.13"
lazy_static = "1.4.0"
metrohash = "1.0"
more-asserts = "0.3"
num_cpus = "1.13.0"
once_cell = "1.21"
openssl = "0.10.72"
parse_duration = "2.1.1"
pin-project = "1.1"
plotters = { version = "0.3", default-features = false, features = ["line_series", "svg_backend", "full_palette"] }
rand = { version = "0.8", default-features = false, features = ["small_rng", "std"] }
rand_distr = "0.4"
regex = "1.5"
rmp = "0.8"
rmp-serde = "1"
rune = "0.13"
rust_decimal = "1.36"
rust-embed = "8"
scylla = { version = "1.4", features = ["openssl-010", "chrono-04"] }
search_path = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
statrs = "0.17"
status-line = "0.2.0"
strum = { version = "0.26", features = ["derive"] }
thiserror = "2.0.0"
time = "0.3"
tokio = { version = "=1.44.2", features = ["rt", "rt-multi-thread", "time", "parking_lot", "signal"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
try-lock = "0.2.3"
uuid = { version = "1.1", features = ["v4"] }
walkdir = "2"



# Platform-specific dependencies
[target.'cfg(not(windows))'.dependencies]
jemallocator = "0.5"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fetch_extended_version_info)'] }
